---
title: "lista5_230532"
author: "Alejandro Figueiredo"
format: pdf
editor: visual
---

```{r}
library(DBI)
library(RSQLite)

# Conecta/Cria o arquivo
con <- dbConnect(RSQLite::SQLite(), "datasets/me315.sqlite")
```


```{sql connection=con}
-- 1
SELECT PNAME, ACRES, (ACRES * 1.20) AS NEWACRES FROM PRESERVE
```

```{sql connection=con}
-- 2
SELECT PNAME, ACRES, (ACRES / 3) AS NEWACRES FROM PRESERVE
```
```{sql connection=con}
-- 3 
SELECT PNAME, FEE, ((FEE + 50)/2) AS NEWFEE FROM PRESERVE
```
```{sql connection=con}
-- 4
SELECT AVG(ACRES), MIN(ACRES), MAX(ACRES) FROM PRESERVE WHERE STATE == 'AZ'

```
```{sql connection=con}
-- 5 
SELECT MIN(PNAME) FROM PRESERVE
```

```{sql connection=con}
-- 6
SELECT COUNT(DISTINCT FEE) FROM PRESERVE WHERE FEE != 0
```
```{sql connection=con}
-- 7
SELECT DISTINCT PNAME FROM PRESERVE
```

```{sql connection=con}
-- 8 
SELECT AVG((ACRES * 0.02)) FROM PRESERVE WHERE STATE = "AZ"
```
```{sql connection=con}
-- 9
SELECT ENO, ENAME, SALARY, (SALARY * 1.10) AS NEWSALARY FROM EMPLOYEE ORDER BY NEWSALARY
```
```{sql connection=con}
-- 10
SELECT ENO, ENAME, SALARY, (SALARY * 1.10) AS NEWSALARY FROM EMPLOYEE WHERE (SALARY * 1.10) > 2000
```
```{sql connection=con}
-- 11

SELECT SUM(SALARY), AVG(SALARY), MAX(SALARY), MIN(SALARY) FROM EMPLOYEE
```
```{sql connection=con}
-- 12
SELECT COUNT(ENAME) FROM EMPLOYEE WHERE DNO == 20
```
```{sql connection=con}
--13
SELECT COUNT(DISTINCT DNO) FROM EMPLOYEE
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```
