---
title: "lista 6"
author: "Alejandro Figueiredo 230352"
format: pdf
editor: visual
---

```{r}
library(DBI)
library(RSQLite)

con <- dbConnect(RSQLite::SQLite(), "datasets/me315.sqlite")
```

```{sql connection=con}
--1
SELECT STATE, MIN(ACRES) AS Menor_Valor 
FROM PRESERVE 
GROUP BY STATE
```

```{sql connection=con}
--2
SELECT STATE, MAX(ACRES) AS MAIOR_VALOR
FROM PRESERVE
WHERE ACRES < 10000
GROUP BY STATE
```

```{sql connection=con}
--3
SELECT STATE, MAX(ACRES) AS MAIOR_VALOR
FROM PRESERVE
WHERE ACRES < 10000
GROUP BY STATE
ORDER BY MAIOR_VALOR DESC
```
```{sql connection=con}
--4
SELECT STATE, MAX(ACRES)
FROM PRESERVE
GROUP BY STATE
HAVING MAX(ACRES) < 25000
```
```{sql connection=con}
--5
SELECT STATE, MIN(ACRES) AS MENOR_VALOR 
FROM PRESERVE
GROUP BY STATE
HAVING MIN(ACRES) < 100
```

```{sql connection=con}
--6
SELECT STATE, PNAME, MAX(ACRES)
FROM PRESERVE
WHERE ACRES > 1000
GROUP BY STATE
HAVING MAX(ACRES) < 25000
```

```{sql connection=con}
--7
SELECT STATE, SUM(ACRES)
FROM PRESERVE
GROUP BY STATE
HAVING SUM(ACRES) >= 10000 AND SUM(ACRES) <= 50000
```

```{sql connection=con}
--8 
SELECT STATE, AVG(ACRES) AS MEDIA
FROM PRESERVE 
GROUP BY STATE
ORDER BY MEDIA DESC
LIMIT 1;
```
```{sql connection=con}
--9
SELECT DNO, AVG(SALARY)
FROM EMPLOYEE
GROUP BY DNO

```
```{sql connection=con}
--10
SELECT DNO, SUM(SALARY), MAX(SALARY), MIN(SALARY)
FROM EMPLOYEE
GROUP BY DNO
```
```{sql connection=con}
--11
SELECT DNO, COUNT(DNO) AS QUANT_FUNCIONARIOS
FROM EMPLOYEE
WHERE DNO != 40
GROUP BY DNO
```
```{sql connection=con}
--12
SELECT DNO, COUNT(DNO)
FROM EMPLOYEE
GROUP BY DNO
HAVING COUNT(DNO) > 2
```
```{sql connection=con}
--13
SELECT STATE, SUM(ACRES)
FROM PRESERVE 
GROUP BY STATE
UNION ALL
SELECT 'Total', SUM(ACRES)
FROM PRESERVE
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```

