---
title: "lista 4"
author: "Alejandro Figueiredo 230532"
format: pdf
editor: visual
---

```{r}
library(DBI)
library(RSQLite)

# Conecta/Cria o arquivo
con <- dbConnect(RSQLite::SQLite(), "datasets/me315.sqlite")
```

```{sql connection=con}
--1
SELECT * FROM PRESERVE WHERE PNO IN (2,4,6,8,10)
```

```{sql connection=con}
--2
SELECT * FROM PRESERVE WHERE PNAME NOT IN ('DANCING PRAIRIE', 'MULESHOE RANCH', 'MCELWAIN-OLSEN','TATKON')
```

```{sql connection=con}
--3
SELECT * FROM PRESERVE WHERE PNO BETWEEN 3 AND 10
```
```{sql connection=con}
--4
SELECT * FROM PRESERVE WHERE PNO < 3 OR PNO > 10 
```
```{sql connection=con}
--5
SELECT STATE, PNO, ACRES 
FROM PRESERVE 
WHERE STATE NOT IN ('MT','AZ') AND (ACRES < 50 OR ACRES > 800)
ORDER BY PNO DESC;
```

```{sql connection=con}
--6
SELECT PNAME FROM PRESERVE WHERE PNAME LIKE 'D%'
```
```{sql connection=con}
--7
SELECT PNAME FROM PRESERVE WHERE PNAME LIKE '%TOWN%'

```
```{sql connection=con}
--8
SELECT PNAME FROM PRESERVE WHERE PNAME LIKE '%PRAIRIE'

```
```{sql connection=con}
--9
SELECT PNAME FROM PRESERVE WHERE PNAME LIKE '%ING%'

```
```{sql connection=con}
--10
SELECT PNAME FROM PRESERVE WHERE PNAME LIKE '%E'
```
```{sql connection=con}
--11
SELECT PNAME FROM PRESERVE WHERE PNAME LIKE '%ME%'

```
```{sql connection=con}
--12
SELECT PNAME FROM PRESERVE WHERE PNAME LIKE '%M%E%'

```
```{sql connection=con}
--13
SELECT PNAME FROM PRESERVE WHERE PNAME LIKE '_A%'

```
```{sql connection=con}
--14
SELECT PNAME FROM PRESERVE WHERE PNAME LIKE '% %'
```

```{sql connection=con}
--15
SELECT PNAME FROM PRESERVE WHERE
  PNAME LIKE '%FARM%' OR 
  PNAME LIKE '%SWAMP%' OR 
  PNAME LIKE '%PRAIRIE%'

```
```{sql connection=con}
--16
SELECT PNAME FROM PRESERVE WHERE PNAME LIKE '%-%' OR PNAME LIKE '%.%'
```
```{sql connection=con}
--17
SELECT PNAME FROM PRESERVE WHERE PNAME LIKE '____R%' AND PNAME LIKE '%PRAIRIE'
```
```{sql connection=con}
--18 
SELECT * FROM EMPLOYEE WHERE DNO IN (10,40)

```
```{sql connection=con}
--19
SELECT * FROM EMPLOYEE WHERE DNO NOT IN (10,40)
```
```{sql connection=con}
--20
SELECT * FROM EMPLOYEE WHERE SALARY BETWEEN 500 AND 2000

```

```{sql connection=con}
--21
SELECT * FROM EMPLOYEE WHERE SALARY NOT BETWEEN 500 AND 2000
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```

